version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "api/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "auth/"
    schedule:
      interval: "weekly"
